<?php

function roy_insta_menu(){
    $items['roy/instagram'] = array(
        // page title
        'title' => 'Roy Instagram',
        // describe the page for the menu system.  site visitors will not see this
        'description' => 'Simple custom hook_menu() implementation.',
        // function that is called when visiting the new path
        'page callback' => 'drupal_get_form',
        'page arguments' => array('roy_insta_loadpage'),
        // permissions required to view page
        //'access arguments' => array('access content'),
        'access callback' => TRUE
    );  
    return $items;
}

function roy_insta_loadpage($form, &$form_state){

      $form['searchtag'] = array(
      '#type' => 'textfield',
      '#title' => 'Search a Tag',
      '#size' => 10,
      '#maxlength' => 50,
      '#required' => TRUE,
      );
      
      $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Search'),
          '#title' => 'Search'
      );
      
    $url = 'https://api.instagram.com/v1/tags/nature/media/recent?client_id=c009ac352f59439ab860fb57958e54c9';

    if (isset($form_state['txttag'])) {
        $url = 'https://api.instagram.com/v1/tags/'.$form_state['txttag'].'/media/recent?client_id=c009ac352f59439ab860fb57958e54c9';
    }
      
    $insta_result = drupal_http_request($url);
    $roy_json = drupal_json_decode($insta_result->data, true);

    $insta = array();
    foreach($roy_json['data'] as $info) {
    
        $imgpath = $info['images']['standard_resolution']['url'];
        $caption = $info['caption']['text'];

        $insta[] = array(
            'imgpath' => $imgpath,
            'caption' => $caption
        );
    }
    $form['roy_insta_table'] = array(
    '#markup' => theme('load_custom_template', array('insta' => $insta))
    );
      return $form;
}

function roy_insta_theme(){
    return array(
        'load_custom_template' => array(
            // load template roy-page.tpl.php
            'template' => 'roy-page',
        ),
    );
}

function roy_insta_loadpage_submit($form, &$form_state) {
    $searchtag = $form_state['values']['searchtag'];
    $form_state['txttag'] = $searchtag;
    $form_state['rebuild'] = TRUE;
}